/* Autogenerated file. Do not edit manually. */

export const IERC7786AttributesABI = [
  {
    type: 'function',
    name: 'executionAddress',
    inputs: [
      {
        name: '_executionAddress',
        type: 'bytes',
        internalType: 'bytes',
      },
    ],
    outputs: [],
    stateMutability: 'pure',
  },
  {
    type: 'function',
    name: 'indirectCall',
    inputs: [
      {
        name: '_indirectCallMessageValue',
        type: 'uint256',
        internalType: 'uint256',
      },
    ],
    outputs: [],
    stateMutability: 'pure',
  },
  {
    type: 'function',
    name: 'interopCallValue',
    inputs: [
      {
        name: '_interopCallValue',
        type: 'uint256',
        internalType: 'uint256',
      },
    ],
    outputs: [],
    stateMutability: 'pure',
  },
  {
    type: 'function',
    name: 'unbundlerAddress',
    inputs: [
      {
        name: '_unbundlerAddress',
        type: 'bytes',
        internalType: 'bytes',
      },
    ],
    outputs: [],
    stateMutability: 'pure',
  },
] as const;

export default IERC7786AttributesABI;
