/* Autogenerated file. Do not edit manually. */

export const IInteropCenterABI = [
  {
    type: 'function',
    name: 'forwardTransactionOnGatewayWithBalanceChange',
    inputs: [
      {
        name: '_chainId',
        type: 'uint256',
        internalType: 'uint256',
      },
      {
        name: '_canonicalTxHash',
        type: 'bytes32',
        internalType: 'bytes32',
      },
      {
        name: '_expirationTimestamp',
        type: 'uint64',
        internalType: 'uint64',
      },
      {
        name: '_balanceChange',
        type: 'tuple',
        internalType: 'struct BalanceChange',
        components: [
          {
            name: 'version',
            type: 'bytes1',
            internalType: 'bytes1',
          },
          {
            name: 'originToken',
            type: 'address',
            internalType: 'address',
          },
          {
            name: 'baseTokenAssetId',
            type: 'bytes32',
            internalType: 'bytes32',
          },
          {
            name: 'baseTokenAmount',
            type: 'uint256',
            internalType: 'uint256',
          },
          {
            name: 'assetId',
            type: 'bytes32',
            internalType: 'bytes32',
          },
          {
            name: 'amount',
            type: 'uint256',
            internalType: 'uint256',
          },
          {
            name: 'tokenOriginChainId',
            type: 'uint256',
            internalType: 'uint256',
          },
        ],
      },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'initL2',
    inputs: [
      {
        name: '_l1ChainId',
        type: 'uint256',
        internalType: 'uint256',
      },
      {
        name: '_owner',
        type: 'address',
        internalType: 'address',
      },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'sendBundle',
    inputs: [
      {
        name: '_destinationChainId',
        type: 'bytes',
        internalType: 'bytes',
      },
      {
        name: '_callStarters',
        type: 'tuple[]',
        internalType: 'struct InteropCallStarter[]',
        components: [
          {
            name: 'to',
            type: 'bytes',
            internalType: 'bytes',
          },
          {
            name: 'data',
            type: 'bytes',
            internalType: 'bytes',
          },
          {
            name: 'callAttributes',
            type: 'bytes[]',
            internalType: 'bytes[]',
          },
        ],
      },
      {
        name: '_bundleAttributes',
        type: 'bytes[]',
        internalType: 'bytes[]',
      },
    ],
    outputs: [
      {
        name: '',
        type: 'bytes32',
        internalType: 'bytes32',
      },
    ],
    stateMutability: 'payable',
  },
  {
    type: 'event',
    name: 'InteropBundleSent',
    inputs: [
      {
        name: 'l2l1MsgHash',
        type: 'bytes32',
        indexed: false,
        internalType: 'bytes32',
      },
      {
        name: 'interopBundleHash',
        type: 'bytes32',
        indexed: false,
        internalType: 'bytes32',
      },
      {
        name: 'interopBundle',
        type: 'tuple',
        indexed: false,
        internalType: 'struct InteropBundle',
        components: [
          {
            name: 'version',
            type: 'bytes1',
            internalType: 'bytes1',
          },
          {
            name: 'sourceChainId',
            type: 'uint256',
            internalType: 'uint256',
          },
          {
            name: 'destinationChainId',
            type: 'uint256',
            internalType: 'uint256',
          },
          {
            name: 'interopBundleSalt',
            type: 'bytes32',
            internalType: 'bytes32',
          },
          {
            name: 'calls',
            type: 'tuple[]',
            internalType: 'struct InteropCall[]',
            components: [
              {
                name: 'version',
                type: 'bytes1',
                internalType: 'bytes1',
              },
              {
                name: 'shadowAccount',
                type: 'bool',
                internalType: 'bool',
              },
              {
                name: 'to',
                type: 'address',
                internalType: 'address',
              },
              {
                name: 'from',
                type: 'address',
                internalType: 'address',
              },
              {
                name: 'value',
                type: 'uint256',
                internalType: 'uint256',
              },
              {
                name: 'data',
                type: 'bytes',
                internalType: 'bytes',
              },
            ],
          },
          {
            name: 'bundleAttributes',
            type: 'tuple',
            internalType: 'struct BundleAttributes',
            components: [
              {
                name: 'executionAddress',
                type: 'bytes',
                internalType: 'bytes',
              },
              {
                name: 'unbundlerAddress',
                type: 'bytes',
                internalType: 'bytes',
              },
            ],
          },
        ],
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'NewAssetRouter',
    inputs: [
      {
        name: 'oldAssetRouter',
        type: 'address',
        indexed: true,
        internalType: 'address',
      },
      {
        name: 'newAssetRouter',
        type: 'address',
        indexed: true,
        internalType: 'address',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'NewAssetTracker',
    inputs: [
      {
        name: 'oldAssetTracker',
        type: 'address',
        indexed: true,
        internalType: 'address',
      },
      {
        name: 'newAssetTracker',
        type: 'address',
        indexed: true,
        internalType: 'address',
      },
    ],
    anonymous: false,
  },
] as const;

export default IInteropCenterABI;
